# Generated by Django 4.1.7 on 2023-04-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduGGV', '0005_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.IntegerField(null=True),
        ),
    ]
