# Generated by Django 4.1.7 on 2023-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduGGV', '0008_remove_course_language_course_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Certificate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
